from django.urls import path

from happ import views

urlpatterns=[
    path('',views.main,name='main'),
    path('hospitalReg',views.hospitalReg,name='hospitalReg'),
    path('hospital_registration',views.hospital_registration,name='hospital_registration'),
    path('patientReg',views.patientReg,name='patientReg'),
    path('patient_registration',views.patient_registration,name='patient_registration'),
    path('log',views.log,name='log'),
    path('logout',views.logout,name='logout'),
    path('forgotPass',views.forgotPass,name='forgotPass'),
    path('password_reset',views.password_reset,name='password_reset'),
    #ADMIN
    path('adminHome',views.adminHome,name='adminHome'),
    path('blockUnblockHospital',views.blockUnblockHospital,name='blockUnblockHospital'),
    path('blockHospital/<int:id>',views.blockHospital,name='blockHospital'),
    path('unblockHospital/<int:id>',views.unblockHospital,name='unblockHospital'),
    path('viewComp',views.viewComp,name='viewComp'),
    path('sendReplyComp/<int:id>',views.sendReplyComp,name='sendReplyComp'),
    path('send_Reply_Comp',views.send_Reply_Comp,name='send_Reply_Comp'),
    path('verifyHospital',views.verifyHospital,name='verifyHospital'),
    path('acceptHospital/<int:id>',views.acceptHospital,name='acceptHospital'),
    path('rejectHospital/<int:id>',views.rejectHospital,name='rejectHospital'),
    path('viewPatient',views.viewPatient,name='viewPatient'),
    #HOSPITAL
    path('hospitalHome',views.hospitalHome,name='hospitalHome'),
    path('manageFacilities',views.manageFacilities,name='manageFacilities'),
    path('addFacilities',views.addFacilities,name='addFacilities'),
    path('add_facilities',views.add_facilities,name='add_facilities'),
    path('updateFacilities',views.updateFacilities,name='updateFacilities'),
    path('delFacility/<int:id>',views.delFacility,name='delFacility'),
    path('editFacilities/<int:id>',views.editFacilities,name='editFacilities'),
    path('manageDepartment',views.manageDepartment,name='manageDepartment'),
    path('addDepartment',views.addDepartment,name='addDepartment'),
    path('add_department',views.add_department,name='add_department'),
    path('editDepartment/<int:id>',views.editDepartment,name='editDepartment'),
    path('delDepartment/<int:id>',views.delDepartment,name='delDepartment'),
    path('updateDepartment',views.updateDepartment,name='updateDepartment'),
    path('manageDoctor',views.manageDoctor,name='manageDoctor'),
    path('addDoctor',views.addDoctor,name='addDoctor'),
    path('add_doctor',views.add_doctor,name='add_doctor'),
    path('docExist',views.docExist,name='docExist'),
    path('editDoctor/<int:id>',views.editDoctor,name='editDoctor'),
    path('delDoc/<int:id>',views.delDoc,name='delDoc'),
    path('updateDoctor',views.updateDoctor,name='updateDoctor'),
    path('viewSchedule',views.viewSchedule,name='viewSchedule'),
    path('viewBooking',views.viewBooking,name='viewBooking'),
    path('manageLab',views.manageLab,name='manageLab'),
    path('addLab',views.addLab,name='addLab'),
    path('add_lab',views.add_lab,name='add_lab'),
    path('updateLab',views.updateLab,name='updateLab'),
    path('editLab/<int:id>',views.editLab,name='editLab'),
    path('delLab/<int:id>',views.delLab,name='delLab'),
    #PATIENT
    path('userHome',views.userHome,name='userHome'),
    path('searchHospital',views.searchHospital,name='searchHospital'),
    path('viewDoctor/<int:id>',views.viewDoctor,name='viewDoctor'),
    path('viewFacility/<int:id>',views.viewFacility,name='viewFacility'),
    path('viewPatSchedule/<int:id>',views.viewPatSchedule,name='viewPatSchedule'),
    path('book_shed/<int:id>',views.book_shed,name='book_shed'),
    path('book',views.book,name='book'),
    path('Book',views.Book,name='Book'),
    path('bookSlot',views.bookSlot,name='bookSlot'),
    path('viewBookStatus',views.viewBookStatus,name='viewBookStatus'),
    path('viewSuggestedLab',views.viewSuggestedLab,name='viewSuggestedLab'),
    path('applySuggLab/<int:id>',views.applySuggLab,name='applySuggLab'),
    path('sendComp',views.sendComp,name='sendComp'),
    path('add_comp',views.add_comp,name='add_comp'),
    path('viewRep',views.viewRep,name='viewRep'),
    path('viewDownldPrescription',views.viewDownldPrescription,name='viewDownldPrescription'),
    # path('generate_pdf/<int:id>',views.generate_pdf,name='generate_pdf'),
    path('download-prescription/<int:id>/', views.download_prescription, name='download_prescription'),
    path('viewReport',views.viewReport,name='viewReport'),
    path('search_hospital',views.search_hospital,name='search_hospital'),
    #LAB
    path('labHome', views.labHome, name='labHome'),
    path('viewDrSugg', views.viewDrSugg, name='viewDrSugg'),
    path('manageReport', views.manageReport, name='manageReport'),
    path('addReport/<int:id>', views.addReport, name='addReport'),
    path('add_report', views.add_report, name='add_report'),
    path('updateReport', views.updateReport, name='updateReport'),
    path('editReport/<int:id>', views.editReport, name='editReport'),
    path('view_report/<int:id>', views.view_report, name='view_report'),
    path('manageLabtest', views.manageLabtest, name='manageLabtest'),
    path('addLabTest', views.addLabTest, name='addLabTest'),
    path('add_labtest', views.add_labtest, name='add_labtest'),
    path('delLabtest/<int:id>', views.delLabtest, name='delLabtest'),
    #doctor
    path('doctorHome', views.doctorHome, name='doctorHome'),
    path('manageSchedule', views.manageSchedule, name='manageSchedule'),
    path('addSchedule', views.addSchedule, name='addSchedule'),
    path('add_schedule', views.add_schedule, name='add_schedule'),
    path('updateSchedule', views.updateSchedule, name='updateSchedule'),
    path('editSchedule/<int:id>', views.editSchedule, name='editSchedule'),
    path('delSchedule/<int:id>', views.delSchedule, name='delSchedule'),
    path('viewBookingUpdate', views.viewBookingUpdate, name='viewBookingUpdate'),
    path('appointBook/<int:id>', views.appointBook, name='appointBook'),
    path('rejectBook/<int:id>', views.rejectBook, name='rejectBook'),
    path('managePrescription', views.managePrescription, name='managePrescription'),
    path('addPrescription', views.addPrescription, name='addPrescription'),
    path('delPresc/<int:id>', views.delPresc, name='delPresc'),
    path('uploadPrescription', views.uploadPrescription, name='uploadPrescription'),
    path('suggestLabAndLabtest', views.suggestLabAndLabtest, name='suggestLabAndLabtest'),
    path('viewSuggestedLabsAndLt', views.viewSuggestedLabsAndLt, name='viewSuggestedLabsAndLt'),
    path('suggestbtn', views.suggestbtn, name='suggestbtn'),
    path('viewReportToDoc', views.viewReportToDoc, name='viewReportToDoc'),


]